### ISSUE TITLE
Rearrange the source code, and other changes

### ISSUE THREAD

**Issue by russel** [Opendigitalradio/dablin#12]
So as to enable bringing in a "vendor fork" of the ka9q-fec library, and to add tests to the codebase, I propose creating a src directory and moving all the current source for dablin and dablin_gtk to there.

I propose abandoning the current Makefile system.

Given the Gtk+3 element here do we want a Meson build to exist in parallel with the CMake build. (Having the CMake build is currently critical to be able to use CLion (https://www.jetbrains.com/clion/) for development, but many Gtk+3 projects are abandoning Autotools and Make in favour of Meson, and Ninja).

**Comment by basicmaster** [comment]
A `src` directory indeed makes sense.

Tests are good but I wonder how to test an application like this, as this is not e.g. a conversion tool where one could simply compare the intended output with the actual one and play with the parameters. So testing seems rather difficult at least to me. But if there is nevertheless a good way to do testing, why not.

Yes, removal of the Makefile system is kind of overdue since CMake works well. Thus reducing to one wide-spread build system it is sufficient to stay with that system in my opinion.

**Comment by russel** [comment]
I think the issues in this issue have all been covered by committed pull requests, so I shal close it.
