### ISSUE TITLE
Cosmetic changes not working 100% right

### ISSUE THREAD

**Issue by jpuigs** [Opendigitalradio/dablin#49]
Hi,
I've never programmed in cpp and gtk….  but I've been doing some tests, changing tooltip informations to be available on screen without needing to stop mouse over labels.
But a new label I've created text is not dark, it's grey,
Any idea about what have I done wrong ?

![image](https://user-images.githubusercontent.com/44906458/59807312-b1dae180-92f7-11e9-8664-f64891650ab9.png)

I've just changed 3 files:
dablin_gtk.cpp
dablin_gtk.h
subchannel_sink.h 

[dablin_mod.zip](https://github.com/Opendigitalradio/dablin/files/3308163/dablin_mod.zip)

**Comment by basicmaster** [comment]
Interesting approach...I have been thinking myself how to show this additional information. But as sometimes it is enough to just listen to the radio, I didn't want to "overload" the GUI, so I decided to use the tooltips instead.

Grey instead of black text is shown if a widget is "disabled". This is achieved using the `set_sensitive` call, which is also applied to the info frame here. I suspect you used the DL field as a template - there this is done to be able to distinguish between "no DL" and "empty DL".

I don't understand though why the progress text is grey - here it is rendered with black text.

**Comment by basicmaster** [comment]
Interesting approach...I have been thinking myself how to show this additional information. But as sometimes it is enough to just listen to the radio, I didn't want to "overload" the GUI, so I decided to use the tooltips instead.

Grey instead of black text is shown if a widget is "disabled". This is achieved using the `set_sensitive` call, which is also applied to the info frame here. I suspect you used the DL field as a template - there this is done to be able to distinguish between "no DL" and "empty DL".

I don't understand though why the progress text is grey - here it is rendered with black text.

**Comment by jpuigs** [comment]
thank you. You're right, I took the DL as a tenplate, and of course I copied all fielda, changing its name.
I've modified it, and now it works fine.
I created this Info frame, because I though that the DL frame was bigger than really needed.
If you want to apply something, I attached the 3 files I changed.

Yes, the progress text is grey, but it was already grey before applying my mods. Not my fault  :-P :-P

**Comment by basicmaster** [comment]
As said, for now I will leave the detail info in the tooltips. But I changed the buttons with text to also use images. Also the record status is moved from the tooltip to a separate label, allowing to add tooltips to all buttons that explain the related action (resulting in aa5e9b0d3c68ccb9b76950b805411f5989c6bfa2). So I think I can close here.
