### ISSUE TITLE
Cannot compile under RPI Strech

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/dablin#50]
I wanted to compile the latest master branch, but it fails at dablin_gtk

[dablin_fail.txt](https://github.com/Opendigitalradio/dablin/files/3364098/dablin_fail.txt)

Before, I have updated the system with `sudo apt-get update` and `sudo apt-get upgrade`

In the past I have successfully compiled DABlin v1.9.0-16-g97ae4b4

**Comment by basicmaster** [comment]
Hmm, I just downloaded the [last Raspbian based on Debian Stretch](https://downloads.raspberrypi.org/raspbian/images/raspbian-2019-04-09/2019-04-08-raspbian-stretch.zip) and tried myself, but here compiling works flawlessly. I also installed all available updates.

Compared to your log however, in my case GCC 6.3.0 is used instead of GCC 8.1.0.....so the question arises, why a newer GCC is used in your case. In my case also the `NATIVE_ATOMICS_SUPPORT` tests succeeds. I also don't get any warnings/errors.

**Comment by basicmaster** [comment]
Is there maybe anything new here in the meantime?

**Comment by andimik** [comment]
I tried it again today but same result... The progress percentage was 93%...

**Comment by basicmaster** [comment]
My question was rather intended to ask for an answer why you have a different GCC version ;-) Did you install/update it somehow? Could you please provide the output of `dpkg -i`? The question is also which Raspbian version *exactly* you downloaded/use.

**Comment by andimik** [comment]
You were right, it had to do with the newer version. I removed gcc with `sudo apt remove gcc` and used the install instructions from the Readme file.

Now it works. But I can't remember why I ever had to install the newer gcc.

**Comment by basicmaster** [comment]
Strange - but at least the issue is solved now.
