### ISSUE TITLE
MOT charset 5 is not supported - Slide disappears right after displaying

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/dablin#58]
Servus Stefan,

the Slovakian DAB seems to use another charset. Maybe this file helps you to integrate it into future versions?

Another strange behavior: If you play it with `dablin_gtk pack12c1.eti -L -l "Radio Slovensko"` then the (first) slide appears and only a few moments it disappears again.

[pack12c1.eti.zip](https://github.com/Opendigitalradio/dablin/files/4078081/pack12c1.eti.zip)

Hint: It's obviously not error-free (although eti-cmdline was 100% all the time), due to the huge distance of around 200 km to the transmitter ...

**Comment by basicmaster** [comment]
Hi Andreas,

> the Slovakian DAB seems to use another charset. Maybe this file helps you to integrate it into future versions?

Similar behaviour can be seen with the service "Radio_FM" and charset 7. The reason here is a buggy slideshow encoder (unfortunately I have already seen this before) that skips the byte which contains the charset - and instead immediately starts with the ContentName. I can't detect this reliably - and this is something that has to be fixed at the source. ;-)

You will also see this when you open the dump in XPADxpert: For Radio Slovensko, a slide is called e.g. "lovensko_320x240.png", as the first byte consists of the charset definition.

> Another strange behavior: If you play it with dablin_gtk pack12c1.eti -L -l "Radio Slovensko" then the (first) slide appears and only a few moments it disappears again.

I noticed/fixed this bug some weeks ago (this also happened with the SWR services which have a different dynamic PTY during the top-of-the-hour news). The fix is on the `next` branch with fcbb20285ae606c85ffc24acdb7345c37a71a6f5.

> Hint: It's obviously not error-free (although eti-cmdline was 100% all the time), due to the huge distance of around 200 km to the transmitter ...

Most of the time, it is fine - otherwise you would see way more RS coding messages like `(4)`.

**Comment by andimik** [comment]
Wow, thanks for the explanation! Indeed, I always was wondering about `lovensko_320x240.png`

I've built the latest commit from the `next` branch and confirm it's working, so I close the issue.
