### ISSUE TITLE
Request for release tag

### ISSUE THREAD

**Issue by paraenggu** [Opendigitalradio/dablin#6]
We're packaging dablin on CentOS 7. It would be helpful if you could create a release tag.

Many thanks!

**Comment by paraenggu** [comment]
Thanks a lot! In case your interested, you'll find the Spec file at [radiorabe/centos-rpm-dablin](https://github.com/radiorabe/centos-rpm-dablin)

**Comment by basicmaster** [comment]
Great! In case a new minor/major release is ready, does your repo get updated automatically by some means?

I saw that you use FDK-AAC instead of FAAD2 for AAC decoding. In this case you can remove FAAD2 from the list of dependencies as the implementations of the two possible AAC decoders are completely separated in the code (I will add a hint to the README regarding the requirements).

Or you could just keep the FAAD2 default (which is my recommendation if there is no specific reason to use FDK-AAC).

**Comment by paraenggu** [comment]
> Great! In case a new minor/major release is ready, does your repo get updated automatically by some means?

No, it's currently updated manually, although the build is automated via OBS.


> I saw that you use FDK-AAC instead of FAAD2 for AAC decoding. In this case you can remove FAAD2 from the list of dependencies

Thanks for spotting this, it was a leftover from the previous version, before I had dablin compiled against your  FDK-AAC library.


> Or you could just keep the FAAD2 default (which is my recommendation if there is no specific reason to use FDK-AAC).

There was no specific reason, I just thought that It would be better to use Opendigitalradio's version of the FDK-AAC library, so that all tools use the same library. Isn't that the case?

**Comment by basicmaster** [comment]
> There was no specific reason, I just thought that It would be better to use Opendigitalradio's version of the FDK-AAC library, so that all tools use the same library. Isn't that the case?

The FDK-AAC option is rather a proof of concept and not tested with as many different formats as the FAAD2 default. So when used with a seldom combination of AAC flavour and sample rate it may crash. I added the option just because of the Opendigitalradio fork of FDK-AAC.

Another strong reason for FAAD2 was that it is available (at least at Ubuntu) from the default packet sources and a priori has been designed for PC usage (in contrast to the original FDK-AAC which had been derived from the Android sources at that time AFAIK).

**Comment by paraenggu** [comment]
OK, thanks for the info, we will consider switching back to FAAD2 then...
